-- MySQL Script generated by MySQL Workbench
-- Fri Jun  6 14:41:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eps_salud_universal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eps_salud_universal` ;

-- -----------------------------------------------------
-- Schema eps_salud_universal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eps_salud_universal` DEFAULT CHARACTER SET utf8mb4 ;
USE `eps_salud_universal` ;

-- -----------------------------------------------------
-- Table `eps_salud_universal`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`administradores` (
  `id_admin` INT(11) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `identificacion` ON `eps_salud_universal`.`administradores` (`identificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`paciente` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `tipo_afiliacion` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  `contrasena` VARCHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `identificacion` ON `eps_salud_universal`.`paciente` (`identificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`doctor` (
  `id_doctor` INT(11) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `especialidad` VARCHAR(100) NULL DEFAULT NULL,
  `jornada_laboral` ENUM('Matinal', 'Vespertina') NOT NULL,
  `contrasena` VARCHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_doctor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `identificacion` ON `eps_salud_universal`.`doctor` (`identificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`unidad` (
  `id_unidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `planta` VARCHAR(50) NOT NULL,
  `id_doctor_responsable` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidad`),
  CONSTRAINT `fk_doctor_responsable`
    FOREIGN KEY (`id_doctor_responsable`)
    REFERENCES `eps_salud_universal`.`doctor` (`id_doctor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `id_doctor_responsable` ON `eps_salud_universal`.`unidad` (`id_doctor_responsable` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`cita` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `id_paciente` INT(11) NOT NULL,
  `id_doctor` INT(11) NOT NULL,
  `id_unidad` INT(11) NOT NULL,
  `fecha_cita` DATE NOT NULL,
  `hora_cita` TIME NOT NULL,
  PRIMARY KEY (`id_cita`),
  CONSTRAINT `cita_ibfk_1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `eps_salud_universal`.`paciente` (`id_paciente`),
  CONSTRAINT `cita_ibfk_2`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `eps_salud_universal`.`doctor` (`id_doctor`),
  CONSTRAINT `cita_ibfk_3`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `eps_salud_universal`.`unidad` (`id_unidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_paciente` ON `eps_salud_universal`.`cita` (`id_paciente` ASC) VISIBLE;

CREATE INDEX `id_doctor` ON `eps_salud_universal`.`cita` (`id_doctor` ASC) VISIBLE;

CREATE INDEX `id_unidad` ON `eps_salud_universal`.`cita` (`id_unidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`consulta` (
  `id_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cita` INT(11) NOT NULL,
  `fecha_atencion` DATE NOT NULL,
  `sintomas` TEXT NULL DEFAULT NULL,
  `tratamiento` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_consulta`),
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`id_cita`)
    REFERENCES `eps_salud_universal`.`cita` (`id_cita`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `id_cita` ON `eps_salud_universal`.`consulta` (`id_cita` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eps_salud_universal`.`historia_clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eps_salud_universal`.`historia_clinica` (
  `id_historia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_paciente` INT(11) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id_historia`),
  CONSTRAINT `historia_clinica_ibfk_1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `eps_salud_universal`.`paciente` (`id_paciente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_paciente` ON `eps_salud_universal`.`historia_clinica` (`id_paciente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
